USE moneymanager

--------------------------USERDETAILS STORED PROCEDURE ---------------------------------------------------------------

--INSERT DETAILS
ALTER PROCEDURE SP_GET_USER_DETAILS (@USER_ID INT,@USER_NAME VARCHAR(20),@EMAIL VARCHAR(20),
@PASSWORD VARCHAR(20))
WITH ENCRYPTION
AS
BEGIN
INSERT INTO USER_DETAILS (USER_ID,USER_NAME,EMAIL,PASSWORD,CREATED_DATE,MODIFIED_DATE)
VALUES(@USER_ID,@USER_NAME,@EMAIL,@PASSWORD,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
END
EXEC SP_GET_USER_DETAILS 111,'HELLO','WANDERER@GMAIL.COM','WANDERER@18'
EXEC SP_GET_USER_DETAILS 113,'WORLD','HODOPHILE@GMAIL.COM','HODOPHILE@18'

SELECT * FROM USER_DETAILS


--SEE PARTICULAR DETAILS
ALTER PROCEDURE SP_GET_PTCL_USER_DETAILS (@USER_NAME VARCHAR(20))
WITH ENCRYPTION
AS
BEGIN
SELECT * FROM USER_DETAILS WHERE USER_NAME=@USER_NAME
END

EXEC SP_GET_PTCL_USER_DETAILS 'WORLD'


--SEE ALL DETAILS
ALTER PROCEDURE SP_GET_ALL_USER_DETAILS
WITH ENCRYPTION
AS
BEGIN
SELECT * FROM USER_DETAILS
END
EXEC SP_GET_ALL_USER_DETAILS

--UPDATE PASSWORD
ALTER PROCEDURE SP_UPDATE_PASS_ON_USER_DETAILS(@USER_NAME VARCHAR(20), @PASSWORD VARCHAR(20))
WITH ENCRYPTION
AS
BEGIN
UPDATE USER_DETAILS SET PASSWORD=@PASSWORD,MODIFIED_DATE =CURRENT_TIMESTAMP WHERE USER_NAME=@USER_NAME
END
EXEC SP_UPDATE_PASS_ON_USER_DETAILS 'WORLD','HODPHILE$@5'


-------------------------------------- CATEGORIES STORED PROCEDURE --------------------------------------------------------------

--- INSERT CATEGORIES -----

ALTER PROCEDURE SP_INSERT_CATEGORIES
@ID VARCHAR(30), 
@CNAME VARCHAR(25), 
@CTYPE VARCHAR(30), 
@ISACTIVE BIT
WITH ENCRYPTION
AS
BEGIN
INSERT INTO CATEGORIES(CATEGORY_ID,CATEGORY_NAME,CATEGORY_TYPE,ISACTIVE,CREATED_DATE,MODIFIED_DATE)
     VALUES (@ID,@CNAME,@CTYPE,@ISACTIVE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
END


EXECUTE SP_INSERT_CATEGORIES C4,'SALARY','INCOME'
EXECUTE SP_INSERT_CATEGORIES C7,'SALARY','INCOME',1

SELECT * FROM CATEGORIES

sp_helptext SP_INSERT_CATEGORIES

-------- LIST CATEGORIES ---------------


ALTER PROCEDURE SP_LIST_CATEGORIES
WITH ENCRYPTION
AS
BEGIN
	SELECT * FROM CATEGORIES;
END

EXECUTE SP_LIST_CATEGORIES

--------READ CATEGORIES --------------

ALTER PROCEDURE SP_READ_CATEGORIES
@ID VARCHAR(10)
WITH ENCRYPTION
AS
BEGIN
SELECT * FROM CATEGORIES WHERE CATEGORY_ID = @ID
END

EXEC SP_READ_CATEGORIES C2

--UPDATE PROCEDURE FOR CATEGORY
ALTER PROCEDURE SP_UPDATE_CATEGORIES
@CTYPE VARCHAR(20),
@ID VARCHAR(30),
@CNAME VARCHAR(25),
@ISACTIVE BIT
WITH ENCRYPTION
AS
BEGIN
UPDATE CATEGORIES SET CATEGORY_TYPE = @CTYPE, CATEGORY_NAME = @CNAME ,ISACTIVE = @ISACTIVE, MODIFIED_DATE = CURRENT_TIMESTAMP WHERE CATEGORY_ID = @ID
END

--DELETE PROCEDURE FOR CATEGORY
 ALTER PROCEDURE SP_DELETE_CATEGORIES
 @ID VARCHAR(30)
 WITH ENCRYPTION
 AS
 BEGIN
 DELETE FROM CATEGORIES WHERE CATEGORY_ID = @ID
 END


 ----------------------------------------- TRANSACTION ----------------------------------------------------------

 ALTER PROCEDURE TRANSAC (@TRASAC_ID VARCHAR(10), @TRASAC_NAME VARCHAR(20), @AMOUNT INT, @CATERGORY_ID VARCHAR(20))
 WITH ENCRYPTION
 AS 
 BEGIN 
 INSERT INTO TRANSACT_TABLE(TRANSAC_ID,TRANSAC_NAME, AMOUNT,CATEGORY_ID,CREATED_DATE,MODIFIED_DATE)
 VALUES(@TRASAC_ID,@TRASAC_NAME,@AMOUNT,@CATERGORY_ID,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) 
 END
 EXEC TRANSAC 'T3','DEBIT',5000,'C3'

 ALTER PROCEDURE SP_LIST_TRANSAC
 WITH ENCRYPTION
 AS
 BEGIN
 SELECT*FROM TRANSACT_TABLE
 END 
 EXEC SP_LIST_TRANSAC 

 ALTER PROCEDURE SP_READ_TRANSAC
 @TRANSAC_ID VARCHAR(20)
 WITH ENCRYPTION
 AS 
 BEGIN 
 SELECT*FROM TRANSACT_TABLE WHERE TRANSAC_ID=@TRANSAC_ID 
 END 
 EXEC SP_READ_TRANSAC 'T1'


 -------------------------------------- BUDGET ---------------------------------------------------------------------


 ALTER PROCEDURE SP_BUDGET_INSERT(@CATEGORY_ID VARCHAR(10),@USER_ID VARCHAR(10),
 @AMOUNT NUMERIC, @BUDGET_PLAN VARCHAR(10))
 WITH ENCRYPTION
AS
BEGIN
    INSERT INTO BUDGET(CATEGORY_ID,USER_ID,AMOUNT,BUDGET_PLAN,CREATED_DATE,MODIFIED_DATE)
	VALUES(@CATEGORY_ID,@USER_ID ,@AMOUNT , @BUDGET_PLAN,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
END

EXECUTE SP_BUDGET_INSERT 'C4',111,10000,'WEEKLY'

EXECUTE SP_BUDGET_INSERT 'C3',111,1000,'WEEKLY'


--SELECT
ALTER PROCEDURE SP_BUDGET_LIST
WITH ENCRYPTION
AS
BEGIN
    SELECT * FROM BUDGET
END

EXEC SP_BUDGET_LIST

--UPDATE
ALTER PROCEDURE SP_BUDGET_UPDATE(@CATEGORY_ID VARCHAR(10),@USER_ID VARCHAR(10) ,
                                @AMOUNT NUMERIC , @BUDGET_PLAN VARCHAR(10))
WITH ENCRYPTION
AS
BEGIN 
   UPDATE BUDGET SET USER_ID = @USER_ID,
					 AMOUNT = @AMOUNT ,
					 BUDGET_PLAN = @BUDGET_PLAN,
					 MODIFIED_DATE = CURRENT_TIMESTAMP
				WHERE CATEGORY_ID = @CATEGORY_ID;
END

EXEC SP_BUDGET_UPDATE C4,111,4000,'MONTHLY'


--DELETE
ALTER PROCEDURE SP_BUDGET_DELETE
@CATEGORY_ID VARCHAR(10) 
WITH ENCRYPTION
AS
BEGIN
DELETE FROM BUDGET WHERE CATEGORY_ID = @CATEGORY_ID
END

EXEC SP_BUDGET_DELETE 'C3'

---------------------------------------BANKACCOUNT ----------------------------------
 


ALTER PROCEDURE SP_BANKACCOUNT (@USER_ID   INT,
                              @BNKACT_ID INT,
                              @ACCOUNT_NUMBER INT,
                              @NAME  VARCHAR(20),
                              @BANK  VARCHAR(50),
                              @IFSC_CODE VARCHAR(10),
                              @BALANCE INT)
WITH ENCRYPTION
AS
BEGIN
     INSERT INTO BANK_ACCOUNT(USER_ID,BNKACT_ID,ACCOUNT_NUMBER, NAME,BANK,IFSC_CODE,BALANCE,CREATED_DATE,MODIFIED_DATE)
     VALUES (@USER_ID,@BNKACT_ID,@ACCOUNT_NUMBER,@NAME,@BANK,@IFSC_CODE,@BALANCE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
END

 
EXEC SP_BANKACCOUNT 111,1,987876545,'KOKILA','IOB','IOBA12334',7000
EXEC SP_BANKACCOUNT 112,2,7683821,'KOKILA','SBI','SBIA12784',9000

 

 

---READ ALL---
ALTER PROCEDURE SP_BANKACCOUNT_READALL
WITH ENCRYPTION
AS
BEGIN
     SELECT * FROM BANK_ACCOUNT
END

 

EXEC SP_BANKACCOUNT_READALL

 

---READ PARTICULAR RECORD---
ALTER PROCEDURE SP_PARTICULAR_BANKACCOUNT(@USER_ID INT, @BNKACT_ID INT)
WITH ENCRYPTION
AS
BEGIN
     SELECT * FROM BANK_ACCOUNT WHERE (USER_ID = @USER_ID AND BNKACT_ID = @BNKACT_ID)
END

 

EXEC SP_PARTICULAR_BANKACCOUNT 111,1

---------------------------------WALLET-----------------------------------------


ALTER PROCEDURE SP_WALLETACCOUNT_INSERT (@USER_ID  INT, @AMOUNT INT)
WITH ENCRYPTION
AS
BEGIN
     INSERT INTO WALLET_ACCOUNT(USER_ID,AMOUNT,CREATED_DATE,MODIFIED_DATE)
     VALUES (@USER_ID,@AMOUNT,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
END

 

EXEC SP_WALLETACCOUNT_INSERT 111,2500
EXEC SP_WALLETACCOUNT_INSERT 112,300

 
SELECT * FROM WALLET_ACCOUNT


---- READ ALL
ALTER PROCEDURE SP_WALLETACCOUNT_READALL
WITH ENCRYPTION
AS
BEGIN
    SELECT * FROM WALLET_ACCOUNT
END
EXEC SP_WALLETACCOUNT_READALL

 

------READ PARTICULAR RECORD
ALTER PROCEDURE SP_WALLETACCOUNT_PARTCLREAD @USER_ID INT
WITH ENCRYPTION
AS
BEGIN
    SELECT * FROM WALLET_ACCOUNT WHERE USER_ID = @USER_ID
END

 

EXEC SP_WALLETACCOUNT_PARTCLREAD 112

 

----UPDATE----
ALTER PROCEDURE SP_UPDATE_WALLETACCOUNT (@USER_ID   INT, @AMOUNT INT)
WITH ENCRYPTION
AS
BEGIN
     UPDATE WALLET_ACCOUNT SET AMOUNT = @AMOUNT, MODIFIED_DATE = CURRENT_TIMESTAMP WHERE USER_ID = @USER_ID
END
EXEC SP_UPDATE_WALLETACCOUNT 112,700

 SELECT * FROM WALLET_ACCOUNT 


---DELETE----
ALTER PROCEDURE SP_DELETE_WALLETACCOUNT @USER_ID   INT
WITH ENCRYPTION
AS
BEGIN
    DELETE FROM WALLET_ACCOUNT WHERE USER_ID = @USER_ID
END

EXEC SP_DELETE_WALLETACCOUNT 112
SELECT * FROM WALLET_ACCOUNT










